import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Her tech trail platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-full h-screen flex justify-center items-center">
        <h1>HER TECH TRAIL PLATFORM</h1>
      </section>

    </div>
  )
}

export default Home
